### ISSUE TITLE
Sharing Scores

### ISSUE THREAD

**Issue by Malc901** [dsasp/Easy3DScoreSupport#2]
Great app that is used by most of the archers in our club. When you share scores with a pdf the totals for each archer are correct but the same breakdown by target for the first archer is sent for each archer.

**Comment by dsasp** [comment]
Thanks, for your feedback. Investigating issue.

**Comment by dsasp** [comment]
closed by mistake, investigation in progress

**Comment by dsasp** [comment]
Investigation completed. Bug fix will be included in Easy3DScore V1.8.1

**Comment by dsasp** [comment]
Closing issue. Fix shipped in Easy3DScore V1.8.1.
